workflows:
  graph-app-android:
    name: Build Graph App APK
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    scripts:
      - name: Set up Flutter
        script: |
          flutter doctor -v
          
      - name: Install dependencies
        script: |
          flutter pub get
          
      - name: Build Android APK
        script: |
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk